---
name: BaseCI

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

  mtls:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/mtls
    steps:
      - uses: actions/checkout@v3
      - name: make-certs
        run: ./make-certs.sh
      - name: run-nginx
        run: |
          docker-compose up --build --detach
          sleep 1
          ./run-curl-command.sh
          docker-compose down

  rootca:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/rootca
    steps:
      - uses: actions/checkout@v3
      - name: init-certs
        run: ./init-certs.sh
      - name: make-certs
        run: ./make-certs.sh
      - name: run-nginx
        run: |
          docker-compose up --build --detach
          sleep 1
          ./run-curl-command.sh
          docker-compose down
      - name: renew-cert
        run: ./renew-certs.sh
      - name: revoke-cert
        run: ./revoke-certs.sh
