---
name: Linting

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

  mtls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make-certs
        run: ./services/mtls/make-certs.sh
      - name: run-nginx
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
          service: nginx-web
          workdir: ./services/mtls
          command: run-curl-command.sh
